<?php

/**
 * This is the model base class for the table "review_product_component".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReviewProductComponent".
 *
 * Columns in table "review_product_component" available as properties of the model,
 * followed by relations of table "review_product_component" available as properties of the model.
 *
 * @property integer $id
 * @property integer $review_product_id
 * @property integer $component_id
 * @property string $rating
 * @property string $create_date
 * @property string $update_date
 * @property integer $is_deleted
 * @property string $delete_date
 *
 * @property Component $component
 * @property ReviewProduct $reviewProduct
 */
abstract class BaseReviewProductComponent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'review_product_component';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ReviewProductComponent|ReviewProductComponents', $n);
	}

	public static function representingColumn() {
		return 'rating';
	}

	public function rules() {
		return array(
			array('review_product_id, component_id, rating', 'required'),
			array('review_product_id, component_id, is_deleted', 'numerical', 'integerOnly'=>true),
			array('rating', 'length', 'max'=>3),
			array('create_date, update_date, delete_date', 'safe'),
			array('create_date, update_date, is_deleted, delete_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, review_product_id, component_id, rating, create_date, update_date, is_deleted, delete_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'component' => array(self::BELONGS_TO, 'Component', 'component_id'),
			'reviewProduct' => array(self::BELONGS_TO, 'ReviewProduct', 'review_product_id'),
			'product' => array(self::BELONGS_TO, 'Product', 'review_product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'review_product_id' => null,
			'component_id' => null,
			'rating' => Yii::t('app', 'Rating'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'component' => null,
			'reviewProduct' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('review_product_id', $this->review_product_id);
		$criteria->compare('component_id', $this->component_id);
		$criteria->compare('rating', $this->rating, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('delete_date', $this->delete_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}