<?php

/**
 * This is the model base class for the table "unique_product_attribute".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UniqueProductAttribute".
 *
 * Columns in table "unique_product_attribute" available as properties of the model,
 * followed by relations of table "unique_product_attribute" available as properties of the model.
 *
 * @property integer $id
 * @property integer $category_id
 * @property string $name
 *
 * @property Category $category
 */
abstract class BaseUniqueProductAttribute extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'unique_product_attribute';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UniqueProductAttribute|UniqueProductAttributes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('category_id, name', 'required'),
			array('category_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('id, category_id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'Category', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => null,
			'name' => Yii::t('app', 'Name'),
			'category' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}