<?php

/**
 * This is the model base class for the table "component".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Component".
 *
 * Columns in table "component" available as properties of the model,
 * followed by relations of table "component" available as properties of the model.
 *
 * @property integer $id
 * @property integer $category_id
 * @property string $name
 * @property integer $is_deleted
 * @property string $delete_date
 * @property string $create_date
 * @property string $update_date
 *
 * @property Category $category
 * @property ReviewProductComponent[] $reviewProductComponents
 */
abstract class BaseComponent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'component';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Component|Components', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('category_id, name', 'required'),
			array('category_id, is_deleted', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('delete_date, create_date, update_date', 'safe'),
			array('is_deleted, delete_date, create_date, update_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category_id, name, is_deleted, delete_date, create_date, update_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'Category', 'category_id'),
			'reviewProductComponents' => array(self::HAS_MANY, 'ReviewProductComponent', 'component_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => null,
			'name' => Yii::t('app', 'Name'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'category' => null,
			'reviewProductComponents' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('delete_date', $this->delete_date, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}