<?php

/**
 * This is the model base class for the table "store_product_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StoreProductInfo".
 *
 * Columns in table "store_product_info" available as properties of the model,
 * followed by relations of table "store_product_info" available as properties of the model.
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $store_id
 * @property string $price
 * @property string $url
 * @property string $create_date
 * @property string $update_Date
 *
 * @property Store $store
 * @property Product $product
 */
abstract class BaseStoreProductInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'store_product_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StoreProductInfo|StoreProductInfos', $n);
	}

	public static function representingColumn() {
		return 'price';
	}

	public function rules() {
		return array(
			array('product_id, store_id, price, url', 'required'),
			array('product_id, store_id', 'numerical', 'integerOnly'=>true),
			array('price', 'length', 'max'=>100),
			array('url', 'length', 'max'=>255),
			array('create_date, update_Date', 'safe'),
			array('create_date, update_Date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_id, store_id, price, url, create_date, update_Date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'store' => array(self::BELONGS_TO, 'Store', 'store_id'),
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_id' => null,
			'store_id' => null,
			'price' => Yii::t('app', 'Price'),
			'url' => Yii::t('app', 'Url'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_Date' => Yii::t('app', 'Update Date'),
			'store' => null,
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('store_id', $this->store_id);
		$criteria->compare('price', $this->price, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_Date', $this->update_Date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}