<?php

/**
 * This is the model base class for the table "filter".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Filter".
 *
 * Columns in table "filter" available as properties of the model,
 * followed by relations of table "filter" available as properties of the model.
 *
 * @property integer $id
 * @property integer $category_id
 * @property string $create_date
 *
 * @property Category $category
 * @property FilterValue[] $filterValues
 */
abstract class BaseFilter extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'filter';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Filter|Filters', $n);
	}

	public static function representingColumn() {
		return 'create_date';
	}

	public function rules() {
		return array(
			array('category_id', 'required'),
			array('category_id', 'numerical', 'integerOnly'=>true),
			array('create_date', 'safe'),
			array('create_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category_id, create_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'Category', 'category_id'),
			'filterValues' => array(self::HAS_MANY, 'FilterValue', 'filter_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => null,
			'create_date' => Yii::t('app', 'Create Date'),
			'category' => null,
			'filterValues' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('create_date', $this->create_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}