<?php

/**
 * This is the model base class for the table "scrape_product".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ScrapeProduct".
 *
 * Columns in table "scrape_product" available as properties of the model,
 * followed by relations of table "scrape_product" available as properties of the model.
 *
 * @property integer $id
 * @property integer $category_id
 * @property string $site_category_id
 * @property string $url
 * @property string $attribute
 * @property string $create_date
 * @property string $update_Date
 *
 * @property Category $category
 */
abstract class BaseScrapeProduct extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'scrape_product';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ScrapeProduct|ScrapeProducts', $n);
	}

	public static function representingColumn() {
		return 'site_category_id';
	}

	public function rules() {
		return array(
			array('category_id, site_category_id, url', 'required'),
			array('category_id', 'numerical', 'integerOnly'=>true),
			array('site_category_id', 'length', 'max'=>50),
			array('attribute, create_date, update_Date', 'safe'),
			array('attribute, create_date, update_Date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category_id, site_category_id, url, attribute, create_date, update_Date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'Category', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => null,
			'site_category_id' => Yii::t('app', 'Site Category'),
			'url' => Yii::t('app', 'Url'),
			'attribute' => Yii::t('app', 'Attribute'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_Date' => Yii::t('app', 'Update Date'),
			'category' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('site_category_id', $this->site_category_id, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('attribute', $this->attribute, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_Date', $this->update_Date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}