<?php

/**
 * This is the model base class for the table "brand".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Brand".
 *
 * Columns in table "brand" available as properties of the model,
 * followed by relations of table "brand" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $image
 * @property integer $status
 * @property integer $is_deleted
 * @property string $delete_date
 * @property string $create_date
 * @property string $update_date
 *
 * @property Product[] $products
 */
abstract class BaseBrand extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'brand';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Brand|Brands', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, description', 'required'),
			array('status, is_deleted', 'numerical', 'integerOnly'=>true),
			array('name, image', 'length', 'max'=>100),
			array('description', 'length', 'max'=>5000),
			array('delete_date, create_date, update_date', 'safe'),
			array('image, status, is_deleted, delete_date, create_date, update_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, image, status, is_deleted, delete_date, create_date, update_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'products' => array(self::HAS_MANY, 'Product', 'brand_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'image' => Yii::t('app', 'Image'),
			'status' => Yii::t('app', 'Status'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'products' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('delete_date', $this->delete_date, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}