<?php

/**
 * This is the model base class for the table "message".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Message".
 *
 * Columns in table "message" available as properties of the model,
 * followed by relations of table "message" available as properties of the model.
 *
 * @property integer $id
 * @property integer $message_id
 * @property integer $user_id
 * @property string $subject
 * @property string $message
 * @property integer $status
 * @property integer $is_deleted
 * @property string $delete_date
 * @property string $create_date
 *
 * @property Message $message0
 * @property Message[] $messages
 * @property User $user
 * @property MessageToUser[] $messageToUsers
 */
abstract class BaseMessage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'message';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Message|Messages', $n);
	}

	public static function representingColumn() {
		return 'subject';
	}

	public function rules() {
		return array(
			array('user_id, subject, message, status', 'required'),
			array('message_id, user_id, status, is_deleted', 'numerical', 'integerOnly'=>true),
			array('subject', 'length', 'max'=>100),
			array('delete_date, create_date', 'safe'),
			array('message_id, is_deleted, delete_date, create_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, message_id, user_id, subject, message, status, is_deleted, delete_date, create_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'message0' => array(self::BELONGS_TO, 'Message', 'message_id'),
			'messages' => array(self::HAS_MANY, 'Message', 'message_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'messageToUsers' => array(self::HAS_MANY, 'MessageToUser', 'message_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'message_id' => null,
			'user_id' => null,
			'subject' => Yii::t('app', 'Subject'),
			'message' => Yii::t('app', 'Message'),
			'status' => Yii::t('app', 'Status'),
			'is_deleted' => Yii::t('app', 'Is Deleted'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'create_date' => Yii::t('app', 'Create Date'),
			'message0' => null,
			'messages' => null,
			'user' => null,
			'messageToUsers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('message_id', $this->message_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('subject', $this->subject, true);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('is_deleted', $this->is_deleted);
		$criteria->compare('delete_date', $this->delete_date, true);
		$criteria->compare('create_date', $this->create_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}