<?php

/**
 * This is the model base class for the table "last_view".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LastView".
 *
 * Columns in table "last_view" available as properties of the model,
 * followed by relations of table "last_view" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $review_product_id
 * @property string $create_date
 *
 * @property ReviewProduct $reviewProduct
 * @property User $user
 */
abstract class BaseLastView extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'last_view';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LastView|LastViews', $n);
	}

	public static function representingColumn() {
		return 'create_date';
	}

	public function rules() {
		return array(
			array('user_id, review_product_id', 'required'),
			array('user_id, review_product_id', 'numerical', 'integerOnly'=>true),
			array('create_date', 'safe'),
			array('create_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, review_product_id, create_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'reviewProduct' => array(self::BELONGS_TO, 'ReviewProduct', 'review_product_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'review_product_id' => null,
			'create_date' => Yii::t('app', 'Create Date'),
			'reviewProduct' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('review_product_id', $this->review_product_id);
		$criteria->compare('create_date', $this->create_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}