<?php

/**
 * This is the model base class for the table "filter_value".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FilterValue".
 *
 * Columns in table "filter_value" available as properties of the model,
 * followed by relations of table "filter_value" available as properties of the model.
 *
 * @property integer $id
 * @property integer $filter_id
 * @property integer $unique_id
 * @property string $name
 *
 * @property UniqueProductAttribute $unique
 * @property Filter $filter
 */
abstract class BaseFilterValue extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'filter_value';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FilterValue|FilterValues', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('filter_id, unique_id, name', 'required'),
			array('filter_id, unique_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('id, filter_id, unique_id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'unique' => array(self::BELONGS_TO, 'UniqueProductAttribute', 'unique_id'),
			'filter' => array(self::BELONGS_TO, 'Filter', 'filter_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'filter_id' => null,
			'unique_id' => null,
			'name' => Yii::t('app', 'Name'),
			'unique' => null,
			'filter' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('filter_id', $this->filter_id);
		$criteria->compare('unique_id', $this->unique_id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}