<?php

/**
 * This is the model base class for the table "view_product".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewProduct".
 *
 * Columns in table "view_product" available as properties of the model,
 * followed by relations of table "view_product" available as properties of the model.
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $user_id
 * @property string $ip
 * @property string $create_date
 *
 * @property Product $product
 * @property User $user
 */
abstract class BaseViewProduct extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_product';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewProduct|ViewProducts', $n);
	}

	public static function representingColumn() {
		return 'ip';
	}

	public function rules() {
		return array(
			array('product_id', 'required'),
			array('product_id, user_id', 'numerical', 'integerOnly'=>true),
			array('ip', 'length', 'max'=>100),
			array('create_date', 'safe'),
			array('user_id, ip, create_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_id, user_id, ip, create_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_id' => null,
			'user_id' => null,
			'ip' => Yii::t('app', 'Ip'),
			'create_date' => Yii::t('app', 'Create Date'),
			'product' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('ip', $this->ip, true);
		$criteria->compare('create_date', $this->create_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}